=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/DTD/Producto/producto2/producto2.dtd
<!ELEMENT lista (producto+)>
	<!ELEMENT producto (nombre, fabricante, precio+)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT fabricante (empresa, localidad?)>
			<!ELEMENT empresa (#PCDATA)>
			<!ELEMENT localidad (#PCDATA)>
		<!ELEMENT precio (#PCDATA)>
			<!ATTLIST precio cliente (final|distribuidor) "Sin asignar">

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/DTD/Producto/producto2/producto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista SYSTEM "producto2.dtd">
<lista>
	<producto>
		<nombre>Muñeca de trapo</nombre>
		<fabricante>
			<empresa>Juegolandia SA</empresa>
			<localidad>Valladolid</localidad>
		</fabricante>
		<precio cliente="final">60</precio>
		<precio cliente="distribuidor">40</precio>
	</producto>
	<producto>
		<nombre>Caballito de madera</nombre>
		<fabricante>
			<empresa>Juegolandia SA</empresa>
			<localidad>Valladolid</localidad>
		</fabricante>
		<precio cliente="final">18</precio>
		<precio cliente="distribuidor">12</precio>
	</producto>
	<producto>
		<nombre>Tren madera básico</nombre>
		<fabricante>
			<empresa>Natura SL</empresa>
		</fabricante>
		<precio cliente="final">80</precio>
		<precio cliente="distribuidor">60</precio>
	</producto>
</lista>
