=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/Repaso/repaso.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
	<xs:element name="Lista">
		<xs:complexType> <!-- lista es complejo porque contiene elementos -->
			<xs:sequence>
				<xs:element name="Curso" maxOccurs="unbounded">
					<xs:complexType>  <!-- curso es complejo porque contiene elementos -->
						<xs:sequence>
							<xs:element name="Titulo" type="xs:string"/>
							<xs:element name="Horas" type="xs:nonNegativeInteger"/>
							<xs:element name="edad1" type="xs:positiveInteger"/>
							<xs:element name="edad2" type="xs:nonNegativeInteger"/>
							<xs:element name="edad3" type="xs:positiveInteger" minInclusive="20"/>
							<xs:element name="edad4" type="xs:positiveInteger" minInclusive="5" maxInclusive="7"/>
							<xs:element name="nombre1" type="xs:string"/>
							<xs:element name="nombre2" type="xs:string"/>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="titulo1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="UNO"/>
										<xs:enumeration value="DOS"/>
										<xs:enumeration value="TRES"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="titulo2">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="5"/> 
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="clave1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="A([A-Z]|[0-9])*"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="clave2" type="tipoClave2"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoClave2">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3}[a-z]{2}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/Repaso/repaso.xml
<?xml version="1.0" encoding="utf-8"?>
<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="repaso.xsd">
	<Curso>
		<Titulo>Lenguaje de Marcas</Titulo>
		<Horas>200</Horas>
		<edad1>15</edad1> 			 <!--es un entero-->
		<edad2>0</edad2> 			 <!--es un entero positivo incluido el cero										-->
		<edad3>23</edad3> 			 <!--es un entero mayor que 20													-->
		<edad4>6</edad4> 			 <!--es un entero entre 5 y 7 ambos incluidos									-->
		<nombre1>Alejandro</nombre1> <!--es una cadena de caracteres												-->
		<nombre2>El Kevin</nombre2>  <!--es una cadena de caracteres de longitud mayor de 3							-->
		<titulo1>TRES</titulo1> 	 <!--posibles valores UNO, DOS y TRES											-->
		<titulo2>cinco</titulo2> 	 <!--longitud entre 5 y 10														-->
		<clave1>Arbol</clave1> 		 <!--una cadena que empieza por A. DEFINIR EL TIPO DENTRO						-->	
		<clave2>AEIou</clave2> 		 <!--una cadena con tres letras mayuscula y dos minusculas. DEFINIR EL TIPO FUERA--> 
	</Curso>
</Lista>
