=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/SchemasDel30-3/AlumnosProfesores.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
	<xs:element name="personas">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="alumno">
						<xs:complexType>
							<xs:sequence>
								<xs:group ref="grupoNomInsti"/>
								<xs:element name="grupo" type="xs:string"/>
								<xs:element name="edad" type="xs:integer"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="profesor">
						<xs:complexType>
							<xs:sequence>
								<xs:group ref="grupoNomInsti"/>
								<xs:element name="materia" type="xs:string"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="grupoNomInsti">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="instituto" type="tipoInstituto"/>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="tipoInstituto">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Someso"/>
			<xs:enumeration value="Fernando Wirtz"/>
			<xs:enumeration value="Eusebio"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/SchemasDel30-3/AlumnosProfesores.xml
<?xml version="1.0" encoding="utf-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AlumnosProfesores.xsd">
	<alumno>
		<nombre>Ana</nombre>
		<instituto>Fernando Wirtz</instituto>
		<grupo>SMR1</grupo>
		<edad>20</edad>
	</alumno>
	<alumno>
		<nombre>Ana</nombre>
		<instituto>Fernando Wirtz</instituto>
		<grupo>SMR1</grupo>
		<edad>20</edad>
	</alumno>
	<profesor>
		<nombre>Ana</nombre>
		<instituto>Fernando Wirtz</instituto>
		<materia>Informatica</materia>
	</profesor>
	<profesor>
		<nombre>Pepe</nombre>
		<instituto>Someso</instituto>
		<materia>Matem√°ticas</materia>
	</profesor>
</personas>
<!--
 Usamos grupos de elementos.
 instituto puede ser: Someso, Fernando Wirtz o Eusebio 
 -->
