=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/autores/autores.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
	<xs:element name="autores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="autor" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"/>
							<xs:element name="edad" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/autores/autores.xml
<?xml version="1.0" encoding="utf-8"?>
<autores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="autores.xsd">
	<autor>
		<nombre>Pepito</nombre>
		<edad>12</edad>
	</autor>
	<autor>
		<nombre>Juan</nombre>
		<edad>25</edad>
	</autor>
	<autor>
		<nombre>Ines</nombre>
		<edad>26</edad>
	</autor>
	<autor>
		<nombre>Andres</nombre>
		<edad>20</edad>
	</autor>
</autores>
