=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/ComplexType/boletin3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
	<xs:element name="boletin">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="ciclo" type="xs:string"/>
				<xs:element name="curso" type="xs:integer"/>
				<xs:element name="evaluacion" type="xs:integer"/>
				<xs:element name="cualificacion" type="tipoCualificacion" maxOccurs="2"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="tipoCualificacion">
		<xs:sequence>
			<xs:element name="modulo" type="xs:string"/>
			<xs:element name="curso" type="xs:integer"/>
			<xs:element name="nota" type="tipoNota"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="tipoNota">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="10"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/ComplexType/boletin3.xml
<?xml version="1.0" encoding="utf-8"?>
<boletin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="boletin3.xsd">
     <nombre>Juan Perez</nombre>
     <ciclo>Administraci√≥n Sistemas Inf.</ciclo>
     <curso>1</curso>
     <evaluacion>1</evaluacion>
     <cualificacion>
           <modulo>Lenguajes de Marcas</modulo>
           <curso>1</curso>
           <nota>6</nota>
     </cualificacion>
     <cualificacion>
           <modulo>Bases de Datos</modulo>
           <curso>1</curso>
           <nota>5</nota>
     </cualificacion>
 </boletin>
<!-- La nota es un entero entre 1 y 10 -->
