=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/ComplexType/modulo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
	<xs:element name="Modulo">
		<xs:complexType> 
			<xs:sequence>
				<xs:element name="Nombre" type="xs:string"/>
				<xs:element name="Contidos" maxOccurs="unbounded">
					<xs:complexType>  
						<xs:sequence>
							<xs:element name="Bloque" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Titulo" type="xs:string"/>
										<xs:element name="Descripcion" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="numero" type="xs:integer"/>
									<xs:attribute name="evaluacion" type="tipoEvaluacion"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoEvaluacion">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="3"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/ComplexType/modulo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Modulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="modulo.xsd">
	<Nombre>Redes de Area Local</Nombre>
	<Contidos>
		<Bloque numero="1" evaluacion="2">
			<Titulo>Sistemas de comunicacins</Titulo>
			<Descripcion>Aspectos físicos, protocolos e arquitecturas de redes.</Descripcion>
		</Bloque>
		<Bloque numero="2" evaluacion="1">
			<Titulo>Redes de datos</Titulo>
			<Descripcion>Dispositivos de interconexión de redes locais e de área extensa.</Descripcion>
		</Bloque>
		<Bloque numero="3" evaluacion="3">
			<Titulo>Redes de área local</Titulo>
			<Descripcion>Administración e xestión dunha rede de área local.</Descripcion>
		</Bloque>
		<Bloque numero="4" evaluacion="3">
			<Titulo>Servizos Internet</Titulo>
			<Descripcion>Adm. de servizos que empreguen protocolos estándar en Internet.</Descripcion>
		</Bloque>
	</Contidos>
</Modulo>
<!--
	Modificación: Añadir dos atributos a Bloque: numero y evaluacion (1,2,3)
 -->
