=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/curso de Alejandro Becerra/curso.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		   xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd">
	<xs:element name="Lista">
		<xs:complexType> <!-- lista es complejo porque contiene elementos -->
			<xs:sequence>
				<xs:element name="Curso" maxOccurs="unbounded">
					<xs:complexType>  <!-- curso es complejo porque contiene elementos -->
						<xs:sequence>
							<xs:element name="Titulo" type="xs:string"/>
							<xs:element name="fInicio" type="xs:date"/>
							<xs:element name="Horas" type="xs:nonNegativeInteger"/>
							<xs:element name="precio" type="xs:positiveInteger"/>
							<xs:element name="horaComienzo" type="xs:time"/>
							<xs:element name="horaFin" type="xs:time"/>
							<xs:element name="examen" type="xs:dateTime"/>
							<xs:element name="chuleta" type="xs:boolean"/>
							<xs:element name="turnoTarde" type="xs:boolean"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>


<!--  Estructura:
    Lista: es una secuencia de un solo elemento:curso
         Curso : es una secuencia de dos elementos:titulo y horas. El curso se repite.
              Titulo
              Horas
         Curso
              TÃ­tulo
              Horas
 -->

=== alexbs01/LenguajesDeMarcas/Ejercicios/XML/Schemas/curso de Alejandro Becerra/1curso.xml
<?xml version="1.0" encoding="utf-8"?>
<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="curso.xsd">
	<Curso>
		<Titulo>Lenguaje de Marcas</Titulo>
		<fInicio>2020-02-18</fInicio>
		<Horas>200</Horas>
		<precio>1000000</precio>
		<horaComienzo>11:30:00</horaComienzo>
		<horaFin>13:00:00</horaFin>
		<examen>2020-02-18T11:30:00</examen>
		<chuleta>1</chuleta>
		<turnoTarde>0</turnoTarde>
	</Curso>
	<Curso>
		<Titulo>BBDD</Titulo>
		<fInicio>2020-03-18</fInicio>
		<Horas>210</Horas>
		<precio>1000000</precio>
		<horaComienzo>11:30:00</horaComienzo>
		<horaFin>13:00:00</horaFin>
		<examen>2020-02-18T11:30:00</examen>
		<chuleta>0</chuleta>
		<turnoTarde>1</turnoTarde>
	</Curso>
</Lista>

<!-- Añadir 	 -->
<!-- precio 			>=1 después de Horas. -->
<!-- horaCominezo 		hora a la que se imparte. -->
<!-- horaFin 			hora a la que se termina la clase. -->
<!-- examen				día y hora en la que es el examen. -->
<!-- chuleta			si o no. -->
<!-- turnoTarde			si o no. -->
